# Generated by Django 4.2.16 on 2026-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_priority',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='breach_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolve_risk_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_risk_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
